<?php 
// Main Wrapper holds _POST variables for instructor or student views

// send redirect back for next launch ********* MOVE TO separate file ???
if (isset ($_REQUEST['addr']))
{
	$url = $_REQUEST['addr'];//form input hidden//['launch_presentation_return_url'];
	$url.=$_REQUEST['item1'];
	$url.='&url=';
	// encode the tool url plus ?media=#
	$query = urlencode( ($_REQUEST['toolurl'].$_REQUEST['medianum']) );
	$url.=$query;
/*	
	echo ("<script>console.log('returned_url:');</script>");
	echo ("<script>console.log('". $url ."');</script>");
*/
	/*returned_url: //https://www.edu-apps.org/extensions/content.html
https://uvu.instructure.com/courses/374381/external_content/success/external_tool_dialog?return_type=lti_launch_url&url=https%3A%2F%2Fmediafiles.uvu.edu%2Faviation%2Ftool%2Fmediatool.php%26media%3D27
	*/

	header("Location: ".htmlspecialchars($url) );
}
// END: send redirect for next launch **********************


// Load up the Basic LTI Support using code
	require_once 'blti/blti.php';
	$consumer_key=$_POST['oauth_consumer_key'];// use it to look up secret in gradeMedia.php
	$consumer= ['table'=>'consumers','key_column'=>$consumer_key];
	$context = new BLTI($consumer, false, false);// ([table,colm] , usesession, doredirect)

if ( $context->valid ) {
    //print "Context Information:\n\n";
    //print $context->dump();
	
	// prep for grade passback
    // NOT SENT if Role is not viewing as a student
	//http://stackoverflow.com/questions/25532535/sending-grade-data-back-to-lms-using-lti
    $outcome_id = "";
    if(isset($_POST['lis_result_sourcedid'])){
	   $outcome_id = $_POST['lis_result_sourcedid'];//the current STUDENT, in the current assignment, for the gradebook column
    }
	
	$roles = $_POST['ext_roles'];//roles
	// comma delimited array:
	$list = explode(",",$roles);
	//urn:lti:instrole:ims/lis/Instructor,
	//urn:lti:role:ims/lis/ContentDeveloper,
	//urn:lti:role:ims/lis/TeachingAssistant,
	//urn:lti:sysrole:ims/lis/User
	
	$mainrole = explode("/lis/",$list[0]);
	$role = $mainrole[1];// Instructor or Student
	/*echo("<script>console.log('PHP mainrole: ".json_encode($mainrole)."');</script>");*/
	// Student,Teacher,TeachingAssistant, Observer, ...
	//if $role == "Student" only display the content container
	
	// param added to launch_url?media_id=33
	$media_id=$_POST['media'];// default=1 if not set yet
    // generate table dynamically because canvas always chooses the first tool
    $tmp = explode('/',$_SERVER["REQUEST_URI"]);
    $table = $tmp[2].'media';//$context->row["media_table"];
    //GET THE MEDIA TABLE FOR student and instructor views
/*	echo("<script>console.log('media_id: ".$media_id."');</script>");*/
	
	//set which view container is visible:
    if($outcome_id == "") {
        $toolurl  = @( $_SERVER["HTTPS"] != 'on' ) ? 'http://'.$_SERVER["SERVER_NAME"] :  'https://'.$_SERVER["SERVER_NAME"];
        //$toolurl .= ( $_SERVER["SERVER_PORT"] !== 80 ) ? ":".$_SERVER["SERVER_PORT"] : "";//443 secure
        $toolurl .= $_SERVER["REQUEST_URI"];

        // determine 1st or 2nd+ launch for Confirm Selection btn no assignment id if first launch
        $assignmentID = "";
        if(isset($_POST['custom_canvas_assignment_id'])){
            $assignmentID = $_POST['custom_canvas_assignment_id'];
        }
        $api = "https://".$_POST['custom_canvas_api_domain']."/api/v1/";// custom_canvas_api_domain = uvu.instructure.com
        $api = $api.'courses/'.$_POST['custom_canvas_course_id'].'/assignments/'.$_POST['custom_canvas_assignment_id'];
        //https://uvu.instructure.com/api/v1/courses/374381/assignments/2145083
        /*echo("<script>console.log('APIaddr: ".$api."');</script>");*/
        //$addr = $_POST['ext_content_return_url'];// same as
        //$returnAddr = $_POST['launch_presentation_return_url'];// post back launch url for selection
        /*echo("<script>console.log('returnAddr: ".$returnAddr."');</script>");*/
        
        include 'viewInstructor.php';// Design, Preview, html
    /*
        When a new assignment is created, the default media_id = 1
        an html file that says "Media has not been set yet"
        load the media into the #preview div (Instructor View)

        instructor selects media file from UI list generated by media table
        -can filter list by Course [AVSC-2150] media was created for
        -includes a thumbnail of the activity for visual reference
        -will load into preview panel when selected

        click Confirm Selection btn to 
        post back to the launch_presentation_return_url 
        Set/Update the resource_selection link launch_url : returnAddr?media=$media_id #
        To change the url after first launch. 
            Update the assignment external_tool_tag_attributes: { url:
            $api PUT with new url
    */

    } else {
        // prep for grade passback
        if(isset($_POST['lis_outcome_service_url'])){
           $outcome_url= $_POST['lis_outcome_service_url'];// send grade to
        }
        include 'viewStudent.php';// html
        //load the media file in #display div (Student View)
    }

} else {
    $outcome_id='context failed';//only show ERR message or ???
    print "<p style=\"color:red\">Could not establish context: ".$context->message."</p>";
}
?>
